### ISSUE TITLE
`runIfOnlySpecified = true`doesn't seems to be the default

### ISSUE THREAD

**Issue by MangelMaxime** [slaveOftime/Fun.Build#18]
If I have the following pipeline:

```fs
pipeline "Setup" {
    description "Setup the project"
    workingDir __SOURCE_DIRECTORY__

    stage "Repro" {
        run ""
    }
}

tryPrintPipelineCommandHelp ()
```

When running `dotnet fsi build.fsx -- -h` I get this message:

![image](https://user-images.githubusercontent.com/4760796/199947483-045e1ff8-1bf0-4ba0-a12b-0b272ad1b155.png)

So it seems to ask me to call `runIfOnlySpecified true` however, when looking at the doc comment of `runIfOnlySpecified`

![image](https://user-images.githubusercontent.com/4760796/199947653-a524022d-2709-4780-bcd9-724f313bb007.png)

It says that `true` is the default value.

**Comment by MangelMaxime** [comment]
I also found out that `runIfOnlySpecified` needs to be placed at the end of the pipeline.

Would it be possible allow calling it at the anywhere in the CE / at the beginning? My reasoning, is like that I can have all the configuration information at the same place in the pipeline CE.

Example, I can have the `description`, `workingDir`, `runIfOnlySpecified` at the top and then the list of stages. 

```fs
pipeline "Setup" {
    description "Setup the project by (cleaning artefacts, adaptiong the tests files, etc.)"
    workingDir __SOURCE_DIRECTORY__
    runIfOnlySpecified

    Stages.clean
    Stages.adaptTest
}
```

**Comment by albertwoo** [comment]
Yes it needs to to placed at the end because only at that place you can get the whole information of the pipeline. At the end it will transform the pipeline to a unit. So it will not have annoying warning says it is not been used. When you do not write runIfOnlySpecified at the end, the final result will become a pipeline context which you can run it later with your own logic. Or compose them in some way. 

It says true is default is because you can write runIfOnlySpecified without append true or false at the end. It is **specified: Option<bool>** from the tool tip. False is for let it run as default even there is nothing specified at the command lines. But only when you have runIfOnlySpecified it then have chance to run. Otherwise it will not run.

But yes the word is confusing because my English is not that good.😂 Feel free to suggest a new api.

**Comment by albertwoo** [comment]
@MangelMaxime the warning will hanppen when you are not using script. For example in a console app.

Yes, PR to change the docs will be welcomed.


> runIfOnlySpecified = truedoesn't seems to be the default
Cannot make that default without specify runIfOnlySpecified, because we cannot control the pipeline if we do that when we want to. And for me put the runIfOnlySpecified at the end is intended to make it for cli only explicitly. 

```fsharp
let p1 =
    pipeline "123" {
        description "xxxx"
    }

// without runIfOnlySpecified, I can control the pipeline by my own not just for command line.
p1.xxxx
p1.Run()
```

**Comment by albertwoo** [comment]
Close because merged
